# Generated by Django 2.0.2 on 2018-02-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shift',
            field=models.CharField(default=1, help_text='Number between 1 and 25', max_length=2),
            preserve_default=False,
        ),
    ]
