# Generated by Django 2.0.2 on 2018-02-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180226_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prime_1',
            field=models.IntegerField(help_text='First Favorite Prime', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prime_2',
            field=models.IntegerField(help_text='Second Favorite Prime', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shift',
            field=models.IntegerField(help_text='Number between 1 and 25', max_length=2),
        ),
    ]
