# Generated by Django 2.0.2 on 2018-02-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180227_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prime_1',
            field=models.IntegerField(help_text='First Favorite Prime', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prime_2',
            field=models.IntegerField(help_text='Second Favorite Prime', null=True),
        ),
    ]
