# Generated by Django 2.0.2 on 2018-02-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_rsa_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='RSA_n',
        ),
    ]
