# Generated by Django 2.0.2 on 2018-02-27 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_remove_profile_rsa_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSA_public_key', models.IntegerField(help_text='First Favorite Prime', null=True)),
                ('RSA_private_key', models.IntegerField(help_text='Second Favorite Prime', null=True)),
                ('RSA_n', models.IntegerField(help_text='First Favorite Prime', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
