# Generated by Django 2.0.2 on 2018-02-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180227_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='RSA_n',
            field=models.IntegerField(help_text='Modulo n', null=True),
        ),
    ]
