# Generated by Django 2.0.2 on 2018-02-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_rsa_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='RSA_private_key',
            field=models.IntegerField(help_text='Private Key', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='RSA_public_key',
            field=models.IntegerField(help_text='Public Key', null=True),
        ),
    ]
