# Generated by Django 2.0.2 on 2018-02-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0004_entry_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='RSA_modulo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='RSA_public',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='encrypted_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
